config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs, only: %i[index show]
  resources :users, only: %i[index show edit update destroy] do
    resources :blogs, only: [:index], module: :users
  end
  resources :tags, only: %i[index show]

  resources :my, only: :index
  namespace :my do
    resources :blogs
  end

  get '/sign_up', to: 'sign_up#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: :signout

  root 'blogs#index'
end

app/models/blog.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: blogs
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  body       :text             not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :integer          default("draft"), not null
#
# Indexes
#
#  index_blogs_on_author_id  (author_id)
#

class Blog < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :blog_tags, dependent: :destroy
  has_many :tags, through: :blog_tags

  validates :title, presence: true, length: { maximum: 64 }
  validates :body, presence: true, length: { maximum: 10_000 }
  enum status: { draft: 0, published: 1 }

  scope :normal_order, -> { order('blogs.created_at DESC') }

  def editable?(user)
    author == user
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  def index
    @blogs = Blog.published.normal_order.includes(:author, :tags).page(params[:page])
  end

  def show
    @blog = Blog.includes(:author, :tags).find(params[:id])
  end
end

app/controllers/my/blogs_controller.rb
# frozen_string_literal: true

class My::BlogsController < ApplicationController
  before_action :require_signed_in
  before_action :set_blog, only: %i[show edit update destroy]

  def index
    @blogs = current_user.blogs.normal_order.includes(:author, :tags).page(params[:page])
  end

  def new
    @blog_contribution = Form::BlogContribution.new
    @blog_contribution.blog = current_user.blogs.new
  end

  def create
    @blog_contribution = Form::BlogContribution.new(blog_params)
    @blog_contribution.blog = current_user.blogs.new

    if @blog_contribution.save
      redirect_to blog_path(id: @blog_contribution.blog.id), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def show
    # Only before action
  end

  def edit
    @blog_contribution = Form::BlogContribution.build_from(@blog)
  end

  def update
    @blog_contribution = Form::BlogContribution.new(blog_params)

    if @blog_contribution.save
      redirect_to blog_path(id: @blog_contribution.blog.id), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to my_blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

  def set_blog
    @blog = current_user.blogs.includes(:author, :tags).find(params[:id])
  end

  def blog_params
    params
      .require(:form_blog_contribution)
      .permit(:title, :body, :tags_string, :status)
      .merge(author: current_user, blog: @blog)
  end
end

app/controllers/users/blogs_controller.rb
# frozen_string_literal: true

class Users::BlogsController < ApplicationController
  before_action :set_user

  def index
    @blogs = @user.blogs.normal_order.includes(:author, :tags).page(params[:page])
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/views/blogs/_edit_actions.html.haml
%ul.list-inline.mt-3
  - if blog.editable?(current_user)
    %li.list-inline-item
      %a.btn.btn-primary{ href: edit_my_blog_path(blog) } Edit
    %li.list-inline-item
      = link_to 'Destroy', my_blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' }
  %li.list-inline-item
    %a{ href: blogs_path } Back

app/views/blogs/_list.html.haml
%table.table
  %thead
    %tr
      %th Date
      %th Title
      %th Author

  %tbody
    - blogs.each do |blog|
      %tr
        %td.text-nowrap.text-lg-right
          = blog.created_at.to_date
        %td
          = link_to blog.title, blog
          - blog.tags.each do |tag|
            %a.badge.badge-light{ href: tag_path(tag) }= tag.name
        %td.text-nowrap= link_to blog.author.nickname, blog.author

app/views/blogs/index.html.haml
.row
  .col-12
    %h1 Listing blogs

.row
  .col-12
    = render 'list', blogs: @blogs

.row
  .col-12
    = paginate @blogs

app/views/blogs/show.html.haml
.row
  .col-12
    = render 'edit_actions', blog: @blog
.row
  .col-12
    .card
      .card-header
        %h1.card-title.mb-0
          = @blog.title
        .d-inline-flex.mr-auto.my-0
          - @blog.tags.each do |tag|
            %a.badge.badge-light{ href: tag_path(tag) }= tag.name
      .card-body
        .markdown
          = markdown_to_html @blog.body

        %p
          = @blog.status


      .card-footer.text-muted
        Written by
        = link_to @blog.author.nickname, user_path(@blog.author)

.row
  .col-12
    = render 'edit_actions', blog: @blog